name: 🚀 Publish
permissions:
  contents: read
  id-token: write
on:
  workflow_dispatch:
  release:
    types: [released]
jobs:
  publish:
    name: 📦 Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 🛠️ Setup
        uses: $/.github/actions/setup

      - name: 🔨 Build
        run: pnpm build

      - name: 🚀 Publish to registry
        run: pnpm publish --provenance --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
